---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s - %(name)s - [%(funcName)s]:%(lineno)3d - %(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: ERROR
    formatter: simple
    stream: ext://sys.stdout
  logfile:
    level: DEBUG
    formatter: simple
    class: logging.handlers.RotatingFileHandler
    filename: lanscan.log
    maxBytes: 1048576
    backupCount: 1
    encoding: UTF-8
root:
  level: DEBUG
  handlers: [logfile, console]

